config/routes.rb
# This file is a part of Redmine Tags (redmine_tags) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2022 RedmineUP
# http://www.redmineup.com/
#
# redmine_tags is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_tags is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_tags.  If not, see <http://www.gnu.org/licenses/>.

RedmineApp::Application.routes.draw do
  match '/issue_tags/auto_complete/:project_id', to: 'auto_completes#issue_tags', via: :get, as: 'auto_complete_issue_tags'
  match '/wiki_tags/auto_complete/:project_id', to: 'auto_completes#wiki_tags', via: :get, as: 'auto_complete_wiki_tags'
  match 'auto_completes/redmine_tags' => 'auto_completes#redmine_tags', via: :get, as: 'auto_complete_redmine_tags'
  match '/tags/context_menu', to: 'tags#context_menu', as: 'tags_context_menu', via: [:get, :post]
  match '/tags', controller: 'tags', action: 'destroy', via: :delete
end

resources :tags, only: [:edit, :update] do
  collection do
    post :merge
    get :context_menu, :merge
  end
end

get :edit_issue_tags, to: 'issue_tags#edit'
post :update_issue_tags, to: 'issue_tags#update'

app/controllers/tags_controller.rb
# This file is a part of Redmine Tags (redmine_tags) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2022 RedmineUP
# http://www.redmineup.com/
#
# redmine_tags is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_tags is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_tags.  If not, see <http://www.gnu.org/licenses/>.

class TagsController < ApplicationController
  unloadable
  before_action :require_admin
  before_action :find_tag, only: [:edit, :update]
  before_action :bulk_find_tags, only: [:context_menu, :merge, :destroy]

  helper :issues_tags

  def edit
  end

  def destroy
    @tags.each do |tag|
      begin
        tag.reload.destroy
      rescue ::ActiveRecord::RecordNotFound
      end
    end

    redirect_back_or_default(controller: 'settings', action: 'plugin', id: 'redmineup_tags', tab: 'manage_tags')
  end

  def update
    @tag.name = params[:tag][:name] if params[:tag]
    if @tag.save
      flash[:notice] = l(:notice_successful_update)
      respond_to do |format|
        format.html { redirect_to controller: 'settings', action: 'plugin', id: 'redmineup_tags', tab: 'manage_tags' }
        format.xml  {}
      end
    else
      respond_to do |format|
        format.html { render action: 'edit' }
      end
    end
  end

  def context_menu
    @tag = @tags.first if @tags.size == 1
    @back = back_url
    render layout: false
  end

  def merge
    if request.post? && params[:tag] && params[:tag][:name]
      params_hash = params[:tag].respond_to?(:to_unsafe_hash) ? params[:tag].to_unsafe_hash : params
      RedmineCrm::Tagging.transaction do
        tag = RedmineCrm::Tag.find_by_name(params_hash['name']) || RedmineCrm::Tag.create(params_hash)
        RedmineCrm::Tagging.where(tag_id: @tags.map(&:id)).update_all(tag_id: tag.id)
        @tags.select { |t| t.id != tag.id }.each{ |t| t.destroy }
        redirect_to controller: 'settings', action: 'plugin', id: 'redmineup_tags', tab: 'manage_tags'
      end
    end
  end

  private

  def bulk_find_tags
    @tags = RedmineCrm::Tag.joins("JOIN #{RedmineCrm::Tagging.table_name} ON #{RedmineCrm::Tagging.table_name}.tag_id = #{RedmineCrm::Tag.table_name}.id ").
            select("#{RedmineCrm::Tag.table_name}.*, COUNT(DISTINCT #{RedmineCrm::Tagging.table_name}.taggable_id) AS count").
            where(id: params[:id] ? [params[:id]] : params[:ids]).
            group("#{RedmineCrm::Tag.table_name}.id, #{RedmineCrm::Tag.table_name}.name")
    raise ActiveRecord::RecordNotFound if @tags.empty?
  end

  def find_tag
    @tag = RedmineCrm::Tag.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/tags_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine Tags (redmine_tags) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2022 RedmineUP
# http://www.redmineup.com/
#
# redmine_tags is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_tags is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_tags.  If not, see <http://www.gnu.org/licenses/>.

require 'digest/md5'

module TagsHelper
  include RedmineCrm::TagsHelper

  def render_issue_tag_link(tag, options = {})
    filters = [[:issue_tags, '=', tag.name]]
    filters << [:status_id, 'o'] if options[:open_only]
    content =
      if options[:use_search]
        link_to(tag, controller: 'search', action: 'index', id: @project, q: tag.name, wiki_pages: true, issues: true)
      else
        link_to_issue_filter tag.name, filters, project_id: @project
      end
    content << content_tag('span', "(#{tag.count})", class: 'tag-count') if options[:show_count]

    style = RedmineupTags.settings['issues_use_colors'].to_i > 0 ? { class: 'tag-label-color', style: "background-color: #{tag_color(tag)}" } : { class: 'tag-label' }
    content_tag('span', content, style)
  end

  def tag_color(tag)
    tag_name = tag.respond_to?(:name) ? tag.name : tag
    "##{Digest::MD5.hexdigest(tag_name)[0..5]}"
  end

  def render_tags_list(tags, options = {})
    unless tags.nil? || tags.empty?
      content, style = '', options.delete(:style)

      tags = tags.all.to_a if tags.respond_to?(:all)

      case sorting = "#{RedmineupTags.settings['issues_sort_by']}:#{RedmineupTags.settings['issues_sort_order']}"
      when 'name:asc' then   tags.sort! { |a, b| a.name <=> b.name }
      when 'name:desc' then  tags.sort! { |a, b| b.name <=> a.name }
      when 'count:asc' then  tags.sort! { |a, b| a.count <=> b.count }
      when 'count:desc' then tags.sort! { |a, b| b.count <=> a.count }
      # Unknown sorting option. Fallback to default one
      else
        logger.warn "[redmine_tags] Unknown sorting option: <#{sorting}>"
        tags.sort! { |a, b| a.name <=> b.name }
      end

      if style == :list
        list_el, item_el = 'ul', 'li'
      elsif style == :simple_cloud
        list_el, item_el = 'div', 'span'
      elsif style == :cloud
        list_el, item_el = 'div', 'span'
      else
        raise 'Unknown list style'
      end

      content = content.html_safe
      if style == :list && RedmineupTags.settings['issues_sort_by'] == 'name'
        tags.group_by { |tag| tag.name.downcase.first }.each do |letter, grouped_tags|
          content << content_tag(item_el, letter.upcase, class: 'letter', :style => '')
          add_tags(style, grouped_tags, content, item_el, options)
        end
      else
        add_tags(style, tags, content, item_el, options)
      end

      content_tag(list_el, content, class: 'tags-cloud', style: (style == :simple_cloud ? 'text-align: left;' : ''))
    end
  end

  def link_to_issue_filter(title, filters, options = {})
    options.merge! link_to_issue_filter_options(filters)
    link_to title, options
  end

  # returns hash suitable for passing it to the <tt>to_link</tt>
  # === parameters
  # * <i>filters</i> = array of arrays. each child array is an array of strings:
  #                    name, operator and value
  # === example
  # link_to 'foobar', link_to_issue_filter_options [[ :tags, '~', 'foobar' ]]
  #
  # filters = [[ :tags, '~', 'bazbaz' ], [:status_id, 'o']]
  # link_to 'bazbaz', link_to_issue_filter_options filters
  def link_to_issue_filter_options(filters)
    options = {
      controller: 'issues',
      action: 'index',
      set_filter: 1,
      fields: [],
      values: {},
      operators: {}
    }

    filters.each do |f|
      name, operator, value = f
      options[:fields].push(name)
      options[:operators][name] = operator
      options[:values][name] = [value]
    end

    options
  end

  private

  def add_tags(style, tags, content, item_el, options)
    tag_cloud tags, (1..8).to_a do |tag, weight|
      content << ' '.html_safe + content_tag(item_el, render_issue_tag_link(tag, options), class: "tag-nube-#{weight}", style: (style == :simple_cloud ? 'font-size: 1em;' : '')) + ' '.html_safe
    end
  end
end

app/views/tags/_additional_assets.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag(:redmine_tags, plugin: 'redmineup_tags') %>
  <%= javascript_include_tag(:redmine_tags, plugin: 'redmineup_tags') %>
  <%= select2_assets %>
<% end %>

app/views/tags/_general.html.erb
<p>
  <%= label_tag 'settings[issues_sidebar]', l(:issues_sidebar) %>
  <%= select_tag 'settings[issues_sidebar]', options_for_select(%w(none list cloud simple_cloud).collect{|v| [l("issue_tags_sidebar_#{v}"), v]}, @settings['issues_sidebar']) %>
</p>
<p>
  <%= label_tag 'settings[issues_show_count]', l(:issues_show_count) %>
  <%= check_box_tag 'settings[issues_show_count]', 1, 1 == @settings['issues_show_count'].to_i %>
</p>
<p>
  <%= label_tag 'settings[issues_open_only]', l(:issues_open_only) %>
  <%= check_box_tag 'settings[issues_open_only]', 1, 1 == @settings['issues_open_only'].to_i %>
</p>
<p>
  <%= label_tag 'settings[issues_sort_by]', l(:issues_sort_by) %>
  <%= select_tag 'settings[issues_sort_by]', options_for_select(%w(name count).collect{|v| [l("issues_sort_by_#{v}"), v]}, @settings['issues_sort_by']) %>
  <%= select_tag 'settings[issues_sort_order]', options_for_select(%w(asc desc).collect{|v| [l("issues_sort_order_#{v}"), v]}, @settings['issues_sort_order']) %>
</p>
<p>
  <%= label_tag 'settings[tags_suggestion_order]', l(:tags_suggestion_order) %>
  <%= select_tag 'settings[tags_suggestion_order]', options_for_select(%w(name last_created most_used).collect{|v| [l("tags_order_by_#{v}"), v]}, @settings['tags_suggestion_order']) %>
</p>
<p>
  <%= label_tag 'settings[issues_use_colors]', l(:issues_use_colors) %>
  <%= check_box_tag 'settings[issues_use_colors]', 1, 1 == @settings['issues_use_colors'].to_i %>
</p>

app/views/tags/_manage_tags.html.erb
<% tags = Issue.all_tag_counts(:order => :name) %>

<% unless tags.to_a.empty? %>
<table class  = "list issues">
  <thead>
    <tr>
      <th class="checkbox hide-when-print">
        <%= link_to image_tag('toggle_check.png'), {},
                              :onclick => 'toggleIssuesSelection(this); return false;',
                              :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
      </th>
      <th><%= l(:field_name) %></th>
      <th align="center" style="width:10%;"> </th>
    </tr>
  </thead>
  <tbody>
    <% tags.each do |tag| %>
      <tr id="<%= tag.id %>" class="<%= cycle("odd", "even") %> hascontextmenu ">
        <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", tag.id, false, :id => nil) %></td>
        <td><%= render_issue_tag_link(tag) %></td>
        <td class="buttons">
          <%= link_to l(:button_edit), edit_tag_path(tag),
                                         :class => 'icon icon-edit' %>

          <%= link_to l(:button_delete), tags_path(:ids => tag),
                                         :method => :delete,
                                         :confirm => l(:text_are_you_sure),
                                         :class => 'icon icon-del' %>
          </td>

      </tr>

    <% end %>
  </tbody>
</table>
<% if Redmine::VERSION.to_s < '3.4' && Redmine::VERSION::BRANCH == 'stable' %>
  <%= context_menu tags_context_menu_path %>
<% else %>
  <% content_for :header_tags do
    javascript_include_tag('context_menu') + stylesheet_link_tag('context_menu')
  end %>

  <%= javascript_tag do %>
    $(document).ready(function(){
      $('#settings form').data('cmUrl', '<%= tags_context_menu_path %>')
    })
  <% end %>
<% end %>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/tags/_select2_transformation_rules.html.erb
<%= transform_to_select2('issue_tags', url: auto_complete_redmine_tags_url) %>

app/views/tags/_settings.html.erb
<% tags_tabs = [{:name => 'general', :partial => 'tags/general', :label => :label_general},
                {:name => 'manage_tags', :partial => 'tags/manage_tags', :label => :issue_tags_manage_tags}
        ]   %>   


<%= render_tabs tags_tabs %>

<% html_title(l(:label_settings), l(:tags)) -%>  

app/views/tags/context_menu.html.erb
<ul>
  <% if @tag -%>
    <li><%= link_to l(:button_edit), edit_tag_path(@tag),
            :class => 'icon icon-edit' %></li>
  <% else %>
    <li><%= link_to l(:issue_tags_button_merge), merge_tags_path(:ids => @tags.collect(&:id)),
            :class => 'icon icon-tags-merge' %></li>
  <% end %>

    <li><%= link_to l(:button_delete), tags_path(:ids => @tags.collect(&:id), :back_url => @back),
                            :method => :delete, :data => {:confirm => l(:text_are_you_sure)}, :class => 'icon icon-del' %></li>
</ul>

app/views/tags/edit.html.erb
<h2><%= link_to l(:setting_issue_tags), controller: 'settings', action: 'plugin', id: 'redmineup_tags', tab: 'manage_tags' %> &#187; <%=h (l(:issue_tags_tag) + ": " + @tag.name) %></h2>

<%= form_tag(tag_path(@tag, :tab => 'tags'), :class => "tabular", :method => :put) do %>
  <%= error_messages_for 'tag' %>
<div class="box">
<!--[form:optvalue]-->
<p><label for="tag_name"><%=l(:field_name)%></label>
<%= text_field 'tag', 'name'  %></p>


</div>

  <%= submit_tag l(:button_save) %>
<% end %>

app/views/tags/merge.html.erb
<h2>
  <%= link_to l(:setting_issue_tags), :controller => 'settings', :action => 'plugin', :id => 'redmineup_tags', :tab => 'manage_tags' %> &#187; <%= l(:issue_tags_label_merge) %>
</h2>

<%= form_tag(merge_tags_path(:ids => @tags.map(&:id)), :class => "tabular") do %>
  <%= error_messages_for 'tag' %>
  <%= render_tags_list(@tags, {
      :show_count => true,
      :open_only => false,
      :style => :simple_cloud
    }) %>


<div class="box">


<!--[form:optvalue]-->
<p><label for="tag_name"><%=l(:field_name)%></label>
<%= text_field 'tag', 'name', :value => @tags.first.name  %></p>


</div>

  <%= submit_tag l(:button_save) %>
<% end %>